wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/ALDAN_SHIELD_-_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/AMAZONIA_CRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/BALTIC_SHIELD_-_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/BASTAR_CRATON_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/BUNDELKHAND_CRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/CHURCHILL_PROVINCE_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/CONGO_CRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/DHARWAR_CRATON_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/GAWLER_CRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/KAAPVAAL_CRATON_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/LIMPOPO_BELT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/NORTH_ATLANTIC_CRATON_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/NORTH_CHINA_CRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/OKHOTSK-OMOLON_CRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/RAE_CRATON_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/SAO_FRANCISCO_CRATON_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/SARMATIAN_CRATON_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/SIBERIAN_CRATON_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/SINGHBHUM_CRATON_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/SLAVE_PROVINCE_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/SUPERIOR_PROVINCE_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/TANZANIA_CRATON_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/UKRAINIAN_SHIELD_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/WEST_AFRICAN_CRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/WEST_AUSTRALIAN_CRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/WYOMING_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/YANGTZE_BLOCK.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Archean_Cratons_comp/ZIMBABWE_CRATON_ARCHEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Complex_Volcanic_Settings_comp/CENTRAL-NEW_YORK_KIMBERLITES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Complex_Volcanic_Settings_comp/ETNA_SICILY.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Complex_Volcanic_Settings_comp/FINGER_LAKES_FIELD_NEW_YORK.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Complex_Volcanic_Settings_comp/HYBLEAN_OR_IBLEAN_PLATEAU;SICILY.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Complex_Volcanic_Settings_comp/OAXACA;MEXICO.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Complex_Volcanic_Settings_comp/POTIGUAR_BASIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Complex_Volcanic_Settings_comp/USTICA_ISLAND;ITALY.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/AUSTRALIA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/AVANAVERA_LARGE_IGNEOUS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/CENTRAL_ATLANTIC_MAGMATIC_PROVINCE_-_CAMP.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/CHILCOTIN_PLATEAU_BASALTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/COMEI_LARGE_IGNEOUS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/DECCAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/EMEISHAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/ETENDEKA_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/ETHIOPIAN_PLATEAU.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/FRANKLIN_LARGE_IGNEOUS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/GUNBARREL_IGNEOUS_EVENT_-_MAMMOTH-WESTERN_CHANNEL_LARGE_IGNEOUS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/HIGH_ARCTIC_LARGE_IGNEOUS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/KAROO_AND_FERRAR_PROVINCES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/KUONAMKA_LARGE_IGNEOUS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/KUZNETSK_BASIN_OR_KUZBASS_TRAPS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/LAKE_VICTORIA_LARGE_IGNEOUS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/MACKENZIE_LARGE_IGNEOUS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/MADAGASCAR_FLOOD_BASALT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/MAIMECHA-KOTUI_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/MALANI_MAGMATIC_PROVINCE;INDIA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/MARATHON_LARGE_IGNEOUS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/MARNDA_MOORN_LARGE_IGNEOUS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/MATACHEWAN_LARGE_IGNEOUS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/MIDCONTINENT_RIFT_SYSTEM_-_KEWEENAWAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/MIDCONTINENT_RIFT_SYSTEM-KEWEENAWAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/NANDALING_-_YANSHAN_BELT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/NILUFER_UNIT_-_YENISEHIR_ASSOCIATION_-_PONTIDES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/NORTH_ATLANTIC_IGNEOUS_PROVINCE_OR_NAIP.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/NORTH_GREENLAND__PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/PANJAL-SOUTH_QIANGTANG_LARGE_IGNEOUS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/PARANA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/QIANGTANG_FLOOD_BASALT_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/RAJAHMUNDRY_TRAPS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/RAJMAHAL-BENGAL-SYLHET.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/RAMPUR-GARHWAL-MANDI-DARLA_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/SEILAND_IGNEOUS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/SIBERIAN_TRAPS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/SOUTH_TETHYAN_SUTURE_ZONE_-_PAKISTAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/TARIM_LARGE_IGNEOUS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/TIBESTI_VOLCANIC_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/UMKONDO_LARGE_IGNEOUS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/WRANGELLIA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/YELLOWSTONE-SNAKE_RIVER_PLAIN_VOLCANIC_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Continental_Flood_Basalts_comp/YEMEN_PLATEAU.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/AEGEAN_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/AEOLIAN_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/ALEUTIAN_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/ALISITOS_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/ANDEAN_ARC_part1.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/ANDEAN_ARC_part2.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/APENNINIC-MAGHREBIDES_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/BANDA_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/BETIC-RIF_OROGENIC_BELT_OR_GIBRALTAR_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/BISMARCK_ARC_-_NEW_BRITAIN_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/CASCADES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/CENTRAL_AMERICAN_VOLCANIC_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/CHAGAI-RASKOH_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/CHUGACH_ACCRETIONARY_COMPLEX.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/EL_ARCO.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/GREATER_ANTILLES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/HALMAHERA_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/HONSHU_ARC_part1.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/HONSHU_ARC_part2.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/IZU-BONIN_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/KAMCHATKA_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/KERMADEC_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/KOHISTAN-LADAKH_TERRANE_OR_GANGDISE_BELT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/KURILE_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/LESSER_ANTILLES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/LIGURIA-SARDO-TYRRHENIAN_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/LUZON_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/MARIANA_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/MEXICAN_VOLCANIC_BELTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/MIDDLE_AMERICA_TRENCH_-_GUATEMALA_TRENCH.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/NEW_CALEDONIA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/NEW_HEBRIDES_ARC_-_VANUATU_ARCHIPELAGO.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/NEW_ZEALAND.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/OKHOTSK-CHUKOTKA_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/RYUKYU_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/SCOTIA_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/SIERRA_NEVADA_MAGMATIC_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/SIKHOTE-ALIN-SAKHALIN_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/SOLOMON_ISLAND_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/SULAWESI_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/SUNDA_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/TALKEETNA_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/TONGA_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/WESTERN_ALPS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Convergent_Margins_comp/YAP_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Inclusions_comp/MELT_INCLUSIONS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ADRIA_DOMAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/AFGHANISTAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ALPS_SARDINIA_CORSICA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/AMAZONIA_CRATON_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ANATOLIA-IRAN_BELT_-_CENOZOIC_QUATERNARY.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ANATOLIA-IRAN_BELT_-_MESOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ANATOLIA-IRAN_BELT_-_PALEOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ANATOLIA-IRAN_BELT_-_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ANDEAN_BASINS_-_MESOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ANGOLA_SHIELD_MESOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ANGOLA_SHIELD_PALEOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ANGOLA_SHIELD_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ANTARCTICA_-_PALEOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ANTARCTICA_-_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ANTARCTICA_PATAGONIA_-_MESOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ANTARCTICA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ARABIAN-NUBIAN_SHIELD_-_CENOZOIC_QUATERNARY.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ARABIAN-NUBIAN_SHIELD_-_MESOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ARABIAN-NUBIAN_SHIELD_-_PALEOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ARABIAN-NUBIAN_SHIELD_-_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ARAVALLI_CRATON_MESOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ARAVALLI_CRATON_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ARCTIC_ALASKA-CHUKOTKA_MICROPLATE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ATLAS_MOUNTAINS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/AUSTRALIA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/BALTIC_SHIELD_-_PALEOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/BALTIC_SHIELD_-_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/BANGWEULU_BLOCK_IRUMIDE_BELT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/BASTAR_CRATON_MESOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/BASTAR_CRATON_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/BERING_SEA_BASALT_PROVINCE_-_CENOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/BORBOREMA_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CALEDONIDES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CANADIAN_SHIELD_CENOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CANADIAN_SHIELD_MESOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CANADIAN_SHIELD_PALEOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CANADIAN_SHIELD_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CARPATHIAN_BELT_AND_PANNONIAN_BASIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CENTRAL_AFRICAN_FOLD_BELT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CENTRAL_ASIAN_FOLDBELT_-_CENOZOIC_QUATERNARY_part1.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CENTRAL_ASIAN_FOLDBELT_-_CENOZOIC_QUATERNARY_part2.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CENTRAL_ASIAN_FOLDBELT_-_MESOZOIC_part1.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CENTRAL_ASIAN_FOLDBELT_-_MESOZOIC_part2.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CENTRAL_ASIAN_FOLDBELT_-_PALEOZOIC_part1.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CENTRAL_ASIAN_FOLDBELT_-_PALEOZOIC_part2.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CENTRAL_ASIAN_FOLDBELT_-_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CENTRAL_INDIAN_TECTONIC_ZONE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CIRCUM-PARANA_ALKALINE_VOLCANIC_PROVINCES_-_CENOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CIRCUM-PARANA_ALKALINE_VOLCANIC_PROVINCES_-_MESOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CIRCUM-PARANA_ALKALINE_VOLCANIC_PROVINCES_-_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/COLORADO_PLATEAU.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/CONGO_CRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/DAMARA_OROGEN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/DARFUR_DOME_VOLCANIC_PROVINCE_SUDAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/DHARWAR_CRATON_MESOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/DHARWAR_CRATON_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/DINARIDES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/EAST_SAHARA_SWELL_-_CRETACEOUS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/EQUATORIAL_AFRICAN_CRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ETHIOPIAN_PLATEAU.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/EUROPEAN_OROGENIC_BELT_-_CENOZOIC_QUATERNARY.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/EUROPEAN_OROGENIC_BELT_-_MESOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/EUROPEAN_OROGENIC_BELT_-_PALEOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/EUROPEAN_OROGENIC_BELT_-_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/GREAT_METEOR_OR_NEW_ENGLAND_HOTSPOT_TRACK_OR_CONT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/HELLENIDES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ILLINOIS-KENTUCKY_FLUORSPAR_DISTRICT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/KAAPVAAL_CRATON_MESOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/KAAPVAAL_CRATON_PALEOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/KAAPVAAL_CRATON_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/KASAI_SHIELD_MESOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/KATANGAN_BASIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/KIBARAN_BELT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/KLAMATH_MOUNTAINS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/LIBYA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/LIMPOPO_BELT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/MADAGASCAR_-_CENOZOIC_QUATERNARY.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/MADAGASCAR_-_PALEOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/MADAGASCAR_-_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/MADAGASCAR_SEYCHELLES_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/MAKKOVIK-KETILIDIAN_OROGENIC_BELT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/MAURITANIDES_OROGEN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/MIDCONTINENT_US_KIMBERLITE-CARBONATITE_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/MOZAMBIQUE_MOBILE_BELT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/MUNSTER_BASIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/NAGSSUGTOQIDIAN_MOBILE_BELT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/NAGSSUGTOQIDIAN_OROGEN_BELT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/NAMAQUALAND_NATAL_BELT_CENOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/NAMAQUALAND_NATAL_BELT_MESOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/NAMAQUALAND_NATAL_BELT_PALEOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/NAMAQUALAND_NATAL_BELT_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/NEW_ZEALAND.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/NORTH_AMERICAN_CORDILLERA_-_CENOZOIC-QUATERNARY.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/NORTH_AMERICAN_CORDILLERA_-_MESOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/NORTH_AMERICAN_CORDILLERA_-_PALEOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/NORTH_AMERICAN_CORDILLERA_-_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/NORTH_ATLANTIC_CRATON_MESOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/NORTH_ATLANTIC_CRATON_PALEOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/NORTH_ATLANTIC_CRATON_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/OKHOTSK-CHUKOTKA_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/OLKHON_TERRANE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/PAN-AFRICAN_-_BRASILIANO_BELTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/PARAGUA_CRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/PARNAIBA_SEDIMENTARY_BASIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/PATAGONIA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/PENOKEAN_OROGEN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/RIBEIRA_BELT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/RIO_DE_LA_PLATA_CRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/SAHARAN_METACRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/SAHARAN_PLATFOM.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/SAO_FRANCISCO_CRATON_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/SAO_LUIS_CRATON_CRATON_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/SARMATIAN_CRATON_PALEOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/SARMATIAN_CRATON_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/SIBERIAN_PLATFORM.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/SIERRAS_ARGENTINA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/SINGHBHUM_CRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/SRI_LANKA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/SUL_RIO_GRANDENSE_SHIELD_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/TANZANIA_CRATON_CENOZOIC_QUATERNARY.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/TANZANIA_CRATON_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/TOCANTINS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/TRANS-HUDSON_OROGEN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/TRANS-PECOS_MAGMATIC_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/TRANS-SAHARAN_FOLD_BELT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/TUAREG_SHIELD.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/UBENDIAN_BELT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/UKRAINIAN_SHIELD_PALEOZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/UKRAINIAN_SHIELD_PROTEROZOIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/URALS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/VERKHOYANSK-CHUKOTKA_COLLISION_ZONE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/WEST_AFRICAN_CRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/WEST_AFRICAN_YOUNGER_RING_COMPLEXES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/WYOMING_CRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/YAVAPAI-MAZATZAL_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ZAMBEZI_BELT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Intraplate_Volcanics_comp/ZIMBABWE_CRATON.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/AMPHIBOLES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/APATITES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/CARBONATES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/CHALCOGENIDES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/CLAY_MINERALS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/CLINOPYROXENES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/FELDSPARS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/FELDSPATHOIDES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/GARNETS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/ILMENITES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/MICA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/OLIVINES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/ORTHOPYROXENES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/PEROVSKITES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/PYROXENES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/QUARTZ.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/SPINELS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/TITANITES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Minerals_comp/ZIRCONS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Basin_Flood_Basalts_comp/ARGO_ABYSSAL_PLAIN;INDIAN_OCEAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Basin_Flood_Basalts_comp/EAST_MARIANA_BASIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Basin_Flood_Basalts_comp/NAURU_BASIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Basin_Flood_Basalts_comp/PANAMA_BASIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Basin_Flood_Basalts_comp/PIGAFETTA_BASIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Basin_Flood_Basalts_comp/WHARTON_BASIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/AHU_VOLCANIC_FIELD.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/AMSTERDAM-ST_PAUL.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/ASCENSION.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/AUSTRAL-COOK_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/AZORES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/BALLENY_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/BOUVET.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/CAMEROON_LINE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/CANARY_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/CAPE_VERDE_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/CAROLINE_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/CHRISTMAS_ISLAND_SEAMOUNT_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/COCOS_ISLAND.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/COMOROS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/CROZET_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/DESVENTURADOS_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/EASTER_SEAMOUNT_CHAIN_-_SALAS_Y_GOMEZ_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/FERNANDO_DE_NORONHA_ARCHIPELAGO.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/GALAPAGOS_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/GOUGH_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/HAINAN_ISLAND.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/HAWAIIAN_ARCH_VOLCANIC_FIELDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/HAWAIIAN_ISLANDS_part1.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/HAWAIIAN_ISLANDS_part2.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/HAWAIIAN-EMPEROR_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/HEARD.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/ICELAND.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/JAN_MAYEN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/JUAN_FERNANDEZ_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/KERGUELEN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/MADEIRA_ARCHIPELAGO.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/MARION_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/MARQUESAS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/MASCARENE_ISLANDS_INCL_REUNION.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/MCDONALD_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/PETER_I_ISLAND.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/PITCAIRN-GAMBIER_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/PRINCE_EDWARD_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/REVILLAGIGEDO_ARCHIPELAGO.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/ROSS_ISLAND.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/SAMOAN_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/SCOTT_ISLAND.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/SELVAGEN_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/SOCIETY_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/ST_HELENA_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/TRINDADE-VITORIA_RISE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/TRISTAN_DA_CUNHA_GROUP.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/TUAMOTU_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/TUPA_VOLCANIC_FIELD.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Ocean_Island_Groups_comp/UMU_VOLCANIC_FIELD.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/BERMUDA_RISE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/BRAZIL_BASIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/CAPE_VERDE_RISE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/CARIBBEAN-COLOMBIAN_PLATEAU.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/CUVIER_OR_WALLABY_PLATEAU.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/HESS_RISE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/HIKURANGI_PLATEAU.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/KERGUELEN_PLATEAU.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/MAGELLAN_RISE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/MANIHIKI_PLATEAU.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/MASCARENE_PLATEAU.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/MATSUMAE_PLATEAU.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/MAUD_RISE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/NATURALISTE_PLATEAU.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/ONTONG_JAVA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/RIO_GRANDE_RISE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/SAO_PAULO_PLATEAU.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Oceanic_Plateaus_comp/SHATSKY_RISE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/ANTARCTICA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/APPALACHIANS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/AUSTRALIA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/BASIN_AND_RANGE_-_GREAT_BASIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/EAST_AFRICAN_RIFT_part1.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/EAST_AFRICAN_RIFT_part2.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/GARDAR_PROVINCE_-_GREENLAND.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/GULF_OF_SUEZ_RIFT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/LATE_CRETACEOUS_IBERIAN_IGNEOUS_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/MEXICAN_BASIN_AND_RANGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/MID-AFRICAN_RIFT_SYSTEM.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/OMAN_RIFT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/OSLO-SKAGERRAK_RIFT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/RED_SEA_RIFT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/RIO_GRANDE_RIFT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/ROSS_OROGEN-TRANSANTARCTIC_MOUNTAINS_-_CAMBRIAN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/SICILY_CHANNEL_RIFT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/SORGENFREI-TORNQUIST_ZONE_-_NORTH_SEA_VOLCANIC_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/SOUTHERN_OKLAHOMA_RIFT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rift_Volcanics_comp/VILYUI_RIFT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/ADAKITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/ANDESITE_BASALTIC_part1.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/ANDESITE_BASALTIC_part2.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/ANDESITE_part1.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/ANDESITE_part2.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/ANDESITE_part3.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/ANDESITE_part4.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/ANDESITE_part5.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/ANKARAMITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/BASALT_part1.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/BASALT_part2.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/BASALT_part3.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/BASALT_part4.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/BASALT_part5.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/BASALT_part6.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/BASALT_part7.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/BASALT_part8.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/BASALT_part9.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/BASANITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/BENMOREITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/BONINITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/CARBONATITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/COMENDITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/DACITE_part1.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/DACITE_part2.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/DIABASE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/DIORITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/DOLERITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/DUNITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/FOIDITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/GABBRO.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/GRANITE_part1.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/GRANITE_part2.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/GRANODIORITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/HARZBURGITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/HAWAIITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/KIMBERLITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/KOMATIITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/LAMPROITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/LAMPROPHYRE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/LATITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/LEUCITITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/LHERZOLITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/MELILITITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/MUGEARITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/NEPHELINITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/OCEANITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/ORTHOPYROXENITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/PANTELLERITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/PERIDOTITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/PHONOLITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/PHONOTEPHRITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/PHOSCORITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/PICRITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/PYROXENITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/RHYODACITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/RHYOLITE_part1.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/RHYOLITE_part2.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/RHYOLITE_part3.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/SHOSHONITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/TEPHRITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/THOLEIITE_part1.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/THOLEIITE_part2.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/TONALITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/TRACHYANDESITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/TRACHYBASALT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/TRACHYBASANITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/TRACHYDACITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/TRACHYDOLERITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/TRACHYPHONOLITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/TRACHYTE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Rocks_comp/WEHRLITE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_AEGEAN_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_AEOLIAN_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_ALEUTIAN_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_AMSTERDAM-ST_PAUL.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_ANEWETAK_SEAMOUNT_TRAIL.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_AUSTRAL-COOK_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_AZORES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_BAHIA_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_BATHYMETRISTS_OR_GRIMALDI_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_BETIC-RIF_OROGENIC_BELT_OR_GIBRALTAR_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_BISMARCK_ARC_-_NEW_BRITAIN_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_CANARY_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_CAPE_VERDE_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_CARNEGIE_RIDGE_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_CASTOR_GUYOT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_CHRISTMAS_ISLAND_SEAMOUNT_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_COBB_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_COCOS_ISLAND_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_COCOS_RIDGE_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_COIBA_RIDGE_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_CONTINENTAL_MARGIN_OFFSHORE_CALIFORNIA_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_COSTA_RICA_SEAMOUNT_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_DE_GERLACH_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_DISCOVERY_TABLEMOUNT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_EAST_SHIKOKU_BASIN_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_EASTER_SEAMOUNT_CHAIN_-_SALAS_Y_GOMEZ_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_ENPO_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_EXPLORER_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_FIEBERLING-GUADALUPE_SEAMOUNT_TRAIL.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_FOUNDATION_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_GALAPAGOS_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_GENROKU_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_GILBERT_RIDGE_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_HAWAIIAN_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_HAWAIIAN-EMPEROR_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_HIKURANGI_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_HONSHU_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_IZU-BONIN_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_IZU-BONIN_BACK-ARC_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_JAPANESE_SEAMOUNT_TRAIL.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_JUAN_FERNANDEZ_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_KAMCHATKA.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_KANEI_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_KERGUELEN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_KERMADEC_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_KINAN_ESCARPMENT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_KINAN_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_KURILE_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_KYUSHU-PALAU_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_LESSER_ANTILLES.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_LINE_ISLANDS_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_LORD_HOWE_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_LOUISVILLE_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_LUZON_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_MAGELLAN_SEAMOUNT_TRAIL.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_MALPELO_RIDGE_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_MANJI_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_MARIANA_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_MARIANA_NORTHERN_SEAMOUNT_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_MARIE_BYRD_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_MARION_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_MARQUESAS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_MARSHALL_SEAMOUNT_GROUP.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_MEDITERRANEAN_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_MID-PACIFIC_MOUNTAINS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_MUSICIANS_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_NEW_ENGLAND_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_NEW_HEBRIDES_ARC_-_VANUATU_ARCHIPELAGO.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_NORTH_ATLANTIC_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_PERNAMBUCO_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_PITCAIRN-GAMBIER_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_PRATT-WELKER_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_RALIK_SEAMOUNT_GROUP.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_RATAK_SEAMOUNT_GROUP.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_RED_SEA_SEMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_ROSS_SEA_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_SAMOAN_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_SCOTIA_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_SELVAGEN_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_SHIKOKU_BASIN_FLOOR_NEAR_KINAN_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_SOCIETY_ISLANDS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_SOLITARY_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_SOUTHERN_AZORES_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_SOUTHWESTERN_SEAMOUNT_PROVINCE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_SUNDA_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_TARAVA_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_TASMANTID_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_TOKELAU_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_TONGA_ARC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_TORE-MADEIRA_RISE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_TRINDADE-VITORIA_RISE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_TUVALU_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_TYPHOON_SEAMOUNT_GROUP.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_UJLAN_SEAMOUNTS.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_UNION_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_WAKE_SEAMOUNT_GROUP.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Seamounts_comp/s_YAMATO_SEAMOUNT_CHAIN.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/AGULHAS_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/BOLLONS_FRACTURE_ZONE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/BROKEN_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/CAPE_VERDE_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/CARNEGIE__RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/CHAGOS-LACCADIVE_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/COCOS_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/COIBA_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/COSTA_RICA_RIFT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/EAST_PACIFIC_RISE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/GALAPAGOS_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/ISLAS_ORCADAS_RISE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/J-ANOMALY_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/JUAN_DE_FUCA_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/KARIN_RIDGE;PACIFIC.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/KELI_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/KOLBEINSEY_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/MADAGASCAR_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/MEDITERRANEAN_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/MENDOZA_RIFT.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/MID-ATLANTIC_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/MIDDLE_AMERICA_TRENCH.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/NINETYEAST_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/PACIFIC_ANTARCTIC_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/SOUTH_ATLANTIC_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/SOUTH_WEST_INDIAN_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/SOUTHERN_MOHNS_RIDGE.csv
wget http://georoc.mpch-mainz.gwdg.de/georoc/Csv_Downloads/Submarine_Ridges_comp/WALVIS_RIDGE.csv